#!/usr/bin/python3

import argparse

version = "0.1"
header = f"flingern {version}"

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=header)
    parser.add_argument("path", help="build the website specified by path")
    args = parser.parse_args()
