title: "flingern"
description: "static photography gallery website generator"
author: "Bruno Croci"

images_max_height: 1024
images_quality: 65
thumbs_max_height: 256
thumbs_quality: 30

images_border: 150
thumbs_border: 0

pages:
  - flingern/index.md
  - flingern/other.md
