title: "flingern"
description: "static art gallery website generator"
author: "Bruno Croci"
url: "https://flingern.croci.art/"

images_max_height: 1024
images_quality: 65
thumbs_max_width: 512
thumbs_quality: 30

images_border: 150
thumbs_border: 0

sections:
  - title: "Main"
    pages:
      - "index.md"
      - "flingern/other.md"
  - title: "Docs"
    pages:
      - "docs/gettingstarted.md"
      - "docs/elements.md"
